# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20161006_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_description',
        ),
    ]
