# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_remove_order_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
    ]
